### ISSUE TITLE
ERROR: Bad state: No method stub was called from within `when()`

### ISSUE THREAD

**Issue by godfreycomputing** [atn832/firebase_auth_mocks#18]
After writing a test to verify signInAnonymously() is called I get the error form the title.  This happens on all calls from the MockFirebaseAuth class.

Here is my test:

    NoParams noParams = NoParams();
    UserCredential userCredential;
    test('Should call Firebase Auth Service', () async {
     //arrange
      when(mockFirebaseAuth.signInAnonymously())
          .thenAnswer((_) async => userCredential);
      //act
      await authRemoteServiceFirebaseAuth.signInAnonymously(noParams);
      //assert
      verify(mockFirebaseAuth.signInAnonymously());
    '});`

**Comment by atn832** [comment]
Yes, because we've faked the calls, so you can't mock them anymore. So your test should look like this:

```
NoParams noParams = NoParams();
UserCredential userCredential;
test('Should call Firebase Auth Service', () async {
  //no need to arrange
  expect(mockFirebaseAuth.currentUser, isNull);
  //act
  await authRemoteServiceFirebaseAuth.signInAnonymously(noParams);
  //assert
  expect(mockFirebaseAuth.currentUser, isNotNull);
'});`
```

You can take a look at a full example usage at https://pub.dev/packages/firebase_auth_mocks#usage.

Also, maybe you can refer to the code to see what's already been faked. https://github.com/atn832/firebase_auth_mocks/blob/master/lib/src/firebase_auth_mocks_base.dart
